### ISSUE TITLE
Exclude base language when exporting localization strings

### ISSUE THREAD

**Issue by icodesign** [rootstudiohq/dolphin#5]
Example configuration:
```
baseLanguage: en
localizations:
  - id: app
    path: App/${LANGUAGE}.lproj/Localizable.strings
    format: strings
    languages:
      - en
      - de
      - es
```
